defmodule CompileInfoMacro do
  defmacro print_compile_info(message) do
    # 获取编译时信息
    compile_time = DateTime.utc_now()
    file_name = __CALLER__.file
    line_number = __CALLER__.line
    
    # 创建随机文件名
    random_name = generate_random_filename()
    
    # 编译时信息
    info = %{
      message: unquote(message),
      compile_time: compile_time,
      file: file_name,
      line: line_number,
      random_file: random_name
    }
    
    # 打印编译时信息
    IO.puts("Compile-time Info:")
    IO.puts("Message: #{unquote(message)}")
    IO.puts("File: #{file_name}")
    IO.puts("Line: #{line_number}")
    IO.puts("Compile Time: #{compile_time}")
    IO.puts("Random File Name: #{random_name}")
    
    # 保存信息到随机命名的.ex文件
    save_info_to_file(info, random_name)
    
    # 返回原始表达式（不改变宏的用途）
    quote do
      unquote(message)
    end
  end
  
  defp generate_random_filename do
    # 生成随机字符串作为文件名
    random_string = 
      1..8
      |> Enum.map(fn _ -> Enum.random(?a..?z) end)
      |> List.to_string()
    
    "/workspace/#{random_string}.ex"
  end
  
  defp save_info_to_file(info, file_path) do
    content = """
    # Compile-time Information
    # Generated at: #{info.compile_time}
    # Source file: #{info.file}
    # Source line: #{info.line}
    # Message: #{info.message}
    
    # Random File Name: #{info.random_file}
    
    # This file was generated by CompileInfoMacro at compile time
    """
    
    File.write!(file_path, content)
    IO.puts("Info saved to: #{file_path}")
  end
end

# 示例使用
defmodule TestModule do
  import CompileInfoMacro
  
  def test_function do
    print_compile_info("This is a test message during compilation")
    :ok
  end
end

# 额外示例
defmodule AnotherTest do
  import CompileInfoMacro
  
  defmacro example_macro do
    print_compile_info("Compiling a macro that uses CompileInfoMacro")
    quote do
      :macro_result
    end
  end
  
  def run_test do
    example_macro()
  end
end

# 使用方式说明：
# 
# 1. 在Elixir项目中使用此宏:
#    defmodule MyModule do
#      import CompileInfoMacro
#      
#      def my_function do
#        print_compile_info("Compiling my_function")
#        # 你的函数逻辑
#      end
#    end
#
# 2. 编译时，宏会:
#    - 打印当前文件、行号和时间戳
#    - 生成一个随机命名的.ex文件保存这些信息
#    - 文件保存在/workspace/目录下