import numpy as np

# 创建一个 3x3 的矩阵
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原始矩阵 A:")
print(A)

# 计算矩阵 A 的转置
A_transpose = A.T
print("\n转置矩阵 A':")
print(A_transpose)

# 将结果格式化为类似Julia的输出并写入文件
with open('/workspace/matrix_transpose.jl', 'a') as f:
    f.write(f'\n\n# Output generated by Python script (simulating Julia)\n# Original matrix A:\n# {A}\n# Transpose matrix A\':\n# {A_transpose}')