from fastapi import FastAPI
import uuid

app = FastAPI()

@app.post("/data/")
async def receive_data():
    # Generate a random filename
    random_filename = f"/workspace/data_{uuid.uuid4().hex}.py"
    
    # Example content to write to the file
    file_content = '''# This is a randomly named Python file generated by the FastAPI endpoint.
print("Hello from the generated file!")'''

    # Write the content to the randomly named file
    with open(random_filename, 'w') as f:
        f.write(file_content)
    
    return {"message": f"File saved successfully as {random_filename}", "filename": random_filename}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)