# 创建一个 3x3 的矩阵
A = [1 2 3; 4 5 6; 7 8 9]
println("原始矩阵 A:")
display(A)

# 计算矩阵 A 的转置
A_transpose = A'
println("\n转置矩阵 A':")
display(A_transpose)

# Output generated by Python script (simulating Julia)
# Original matrix A:
# [[1 2 3]
 [4 5 6]
 [7 8 9]]
# Transpose matrix A':
# [[1 4 7]
 [2 5 8]
 [3 6 9]]