// Implementation file for AMyPlayerController
// This file was generated by the AI assistant.

#include "MyPlayerController.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"

AMyPlayerController::AMyPlayerController()
{
}

void AMyPlayerController::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

void AMyPlayerController::SetupInputComponent()
{
	Super::SetupInputComponent();

	// Get the EnhancedInputComponent
	UEnhancedInputComponent* PlayerInputComponent = Cast<UEnhancedInputComponent>(InputComponent);
	if (!PlayerInputComponent) return;

	// Bind actions
	PlayerInputComponent->BindAction(MoveForwardAction, ETriggerEvent::Triggered, this, &AMyPlayerController::MoveForward);
	PlayerInputComponent->BindAction(MoveRightAction, ETriggerEvent::Triggered, this, &AMyPlayerController::MoveRight);
	PlayerInputComponent->BindAction(LookUpAction, ETriggerEvent::Triggered, this, &AMyPlayerController::LookUp);
	PlayerInputComponent->BindAction(TurnAction, ETriggerEvent::Triggered, this, &AMyPlayerController::Turn);
	PlayerInputComponent->BindAction(JumpAction, ETriggerEvent::Started, this, &AMyPlayerController::Jump);
}

void AMyPlayerController::MoveForward(float Value)
{
	// Add forward movement logic here
}

void AMyPlayerController::MoveRight(float Value)
{
	// Add right movement logic here
}

void AMyPlayerController::LookUp(float Value)
{
	// Add look up logic here
}

void AMyPlayerController::Turn(float Value)
{
	// Add turn logic here
}

void AMyPlayerController::Jump()
{
	// Add jump logic here
}