import cv2
import numpy as np

# This script was generated by another script.
# It creates a blank image and saves it.

# Create a blank black image
image = np.zeros((512, 512, 3), dtype=np.uint8)

# Optional: Save the generated image
cv2.imwrite('generated_blank_image.jpg', image)
print("Blank image saved as generated_blank_image.jpg")
