class Puppet:
    """
    A class to represent a Puppet for network configuration.
    """

    def __init__(self, name, ip_address, netmask, gateway):
        """
        Initializes the Puppet with network settings.

        Args:
            name (str): The name of the Puppet.
            ip_address (str): The IP address for the Puppet.
            netmask (str): The subnet mask for the Puppet.
            gateway (str): The default gateway for the Puppet.
        """
        self.name = name
        self.ip_address = ip_address
        self.netmask = netmask
        self.gateway = gateway

    def configure_network(self):
        """
        Simulates network configuration.
        In a real-world scenario, this might execute system commands or API calls.
        """
        print(f"Puppet {self.name} is configuring network with:")
        print(f"  IP Address: {self.ip_address}")
        print(f"  Netmask: {self.netmask}")
        print(f"  Gateway: {self.gateway}")
        # Simulate successful configuration
        return True

    def save_config(self, filename):
        """
        Saves the current network configuration to a file.

        Args:
            filename (str): The name of the file to save the configuration.
        """
        config_data = f"""# Puppet Network Configuration for {self.name}
# Generated by Puppet class

interface eth0
static ip_address={self.ip_address}
static netmask={self.netmask}
static gateway={self.gateway}
"""
        try:
            with open(filename, 'w') as f:
                f.write(config_data)
            print(f"Configuration saved to {filename}")
        except IOError as e:
            print(f"Error saving configuration to {filename}: {e}")
