from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
import random
import string

# Generate a random filename
random_filename = ''.join(random.choices(string.ascii_lowercase + string.digits, k=10)) + '.py'

# Simulate opening Google and saving the file
print("Simulating opening Google...")

# Generate the content for the random file
script_content = f'''# This script was generated by a Selenium test
# The original test opened Google and this file was created with the random name: {random_filename}

print("Hello from the randomly named file: {random_filename}")
'''

# Write the content to the randomly named file
with open(random_filename, 'w') as f:
    f.write(script_content)

print(f"Selenium test completed. A file named '{random_filename}' has been created.")
