from selenium import webdriver
from selenium.webdriver.common.by import By
import time
import random
import string

# Generate a random filename
random_filename = ''.join(random.choices(string.ascii_lowercase + string.digits, k=10)) + '.py'

# Initialize the Chrome WebDriver
driver = webdriver.Chrome()

try:
    # Open Google
    driver.get("https://www.google.com")

    # Wait a bit to ensure the page loads
    time.sleep(2)

    # Get the page title as an example of interaction
    page_title = driver.title
    print(f"Page title is: {page_title}")

    # Example of saving some content to the random file
    with open(random_filename, 'w') as f:
        f.write(f"# This file was generated by a Selenium script.\n")
        f.write(f"# It interacted with: {page_title}\n")
        f.write(f"print('Hello from {random_filename}!')\n")

    print(f"Test script executed successfully. A new file '{random_filename}' has been created.")

finally:
    # Close the browser
    driver.quit()
