import random
import string
from selenium import webdriver
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.firefox.options import Options
from webdriver_manager.firefox import GeckoDriverManager

def generate_random_filename():
    """Generates a random filename with a .py extension."""
    random_name = ''.join(random.choices(string.ascii_letters + string.digits, k=10))
    return f"{random_name}.py"

# Setup Firefox options for headless mode
firefox_options = Options()
firefox_options.add_argument("--headless")  # Run in headless mode

# Setup the Firefox driver using webdriver_manager
service = Service(GeckoDriverManager().install())
driver = webdriver.Firefox(service=service, options=firefox_options)

try:
    # Open Google
    driver.get("https://www.google.com")
    
    # Wait for a few seconds to see the page
    driver.implicitly_wait(5)
    
    # Generate a random filename
    filename = generate_random_filename()
    
    # Save a simple script to the randomly named file
    with open(filename, 'w') as f:
        f.write('print("Hello from the randomly named file!")\n')
        f.write('print("This script was generated by the Selenium test.")\n')
    
    print(f"Selenium test completed. A new file '{filename}' has been created.")

finally:
    # Close the browser
    driver.quit()
