/*
* This file was generated by an AI assistant.
* Please review the configuration before applying it.
*/

resource "aws_instance" "web_server" {
  ami           = "ami-0c55b159cbfafe1d0" # Amazon Linux 2 AMI ID (example)
  instance_type = "t2.micro"               # Instance type

  tags = {
    Name = "WebServer"
  }
}